name: Plato CI

on:
  push:
    paths-ignore:
      - '**.md'

  pull_request:
    paths-ignore:
      - '**.md'

env:
  CARGO_TERM_COLOR: always

jobs:
  plato-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Plato
      run: |
        set -eux -o pipefail
        # Check whether the dependencies are installed
        dpkg-query --show coreutils git jq patch pkg-config tar unzip wget xz-utils
        # Download Linaro GCC
        wget -q https://releases.linaro.org/components/toolchain/binaries/6.5-2018.12/arm-linux-gnueabihf/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf.tar.xz
        # Extract Linaro GCC
        tar --extract --xz --file gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf.tar.xz
        rm --verbose gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf.tar.xz
        mv --verbose gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf/ gcc-linaro/
        # Add to PATH and then check
        export PATH=$(pwd)/gcc-linaro/bin:$PATH
        type arm-linux-gnueabihf-gcc
        # Prepare Rust
        rustup update stable
        rustup default stable
        rustup target add arm-unknown-linux-gnueabihf
        rustup target list | grep installed
        # Run build script
        bash -c ./build.sh
        # Print plato's binary file information, to check its kernel version compatibility specifically
        file target/arm-unknown-linux-gnueabihf/release/plato
